### PR TITLE
don't assume pages have primary categories in templates

### PR DESCRIPTION
**Pull request by Rizziepit**

### CODE REVIEW

**Comment by Rizziepit** [comment]
@miltontony ready for review. Needs a new release of `unicore-cms` to pass.

**Comment by miltontony** [comment]
@Rizziepit can you do a new release of `unicore-cms`?

**Comment by Rizziepit** [comment]
@miltontony I'd like to finish this off https://github.com/universalcore/unicore-cms/issues/103, then release.

**Comment by miltontony** [comment]
:+1:

**Pull request merged**
