### PR TITLE
added home button at the bottom on the bottom navigation

### PR DESCRIPTION
**Pull request by TrevorOctober**
@miltontony @hodgestar Ready for review (https://praekeltorg.atlassian.net/browse/BC-17)

### CODE REVIEW

**Comment by TrevorOctober** [comment]
screenshot from 2016-03-15 13 49 45

**Comment by miltontony** [comment]
:+1:

**Comment by hodgestar** [comment]
@miltontony @TrevorOctober We seem to be missing a space between `Home` and `|`?

**Comment by hodgestar** [comment]
@miltontony @TrevorOctober Ah, it got added later. Nm!

**Pull request merged**
